name = "openfeature"
version = "0.4.2"
description = "The Gleam SDK for the OpenFeature specification."
licences = ["Apache-2.0"]
repository = { type = "github", user = "horvathandris", repo = "openfeature-gleam-sdk" }
gleam = ">= 1.0.0"
# links = [{ title = "Website", href = "https://gleam.run" }]


[dependencies]
gleam_stdlib = "~> 0.30 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
